### ISSUE TITLE
clicli 弹幕网2.0 重构经验分享

### ISSUE THREAD

**Issue by 132yse** [frontend9/fe9-library#147]
halo，大家好，我是吸管(⊙o⊙)…

clicli弹幕网（[clicli.us](https://www.clicli.us)） 是我个人写的弹幕视频网站，这是一个技术栈极为前沿而且骚操作很多的网站
本篇将重点分享前端方面

### 架构
![](https://ws1.sinaimg.cn/large/0065Zy9egy1fwzn527zehj30k008bq2z.jpg)

如图，clicli 的技术栈，差不多是这个样子，前端占比是非常大的，包含了 vue ssr、react spa、node 中间层

### SSR 的极致性能实践

我们在做 ssr 的时候，首当其冲会考虑到性能问题，我们用各种的策略，都是为了同一个结果：减小服务端压力。但是市面上大多数 ssr 实践仍然停留在首屏加载

也就是这个方案：
![](https://dn-coding-net-production-pp.codehub.cn/5454c09c-3d0f-47e9-96e0-2723565c9ff1.jpeg)

因为 ssr 只是用来做 seo 的（它解决加载问题的能力很有限），所以最理想的状态是……百度爬虫 ssr，用户 spa

这个是可以做到的，但是百度并不傻，会直接判定为作弊√

所以最终，我们 clicli 的策略也做了微调——登录状态 spa，未登录 ssr

实现方法也很简单，就是同时打包 spa 和 ssr，登录状态就直接index.html
```JavaScript
if (isLogin) {
    let data = fs.readFileSync(path.join(__dirname, '../dist/spa/index.html'))
    ctx.body = data.toString()
  }
```
然后配合 cdn 和 缓存，这个策略是可以接受的

当然，直到现在，还有一些坑无法解决

**miniCssExtraPlugin 不支持 vue ssr 的 createRender**

这是目前尚未解决的第一个坑，就是这个插件并不支持 ssr，[相关issue在这里](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/90)

暂时没有很好的解决方案，我用了替代的 extra-plugin 来代替它，但是还是想使用 webpack 官方推荐的插件(⊙o⊙)…

**状态管理**

我一直强调，状态管理在 ssr 的重要性和不可替代性，原因是 ssr 的场景比较特殊，我们需要维护的是两端的状态，什么意思？

为了节约性能损耗，我们常常需要有一部分逻辑只在客户端做，服务端不需要，也就是说，两端的状态可以不一样，但是我们又需要维护两端的状态，所以——

![](https://dn-coding-net-production-pp.codehub.cn/d8874665-8322-4ff7-bff0-51070cd0cca1.jpeg)

我们可以无可厚非的在客户端去 setState （对应 vue 的 data），但是服务端肯定不具备这个能力，因为它根本走不到 mounted 的生命周期，所以这个时候，一个必要的状态管理工具就很美好了(⊙o⊙)…

vue 可以是 vuex，react 嘛，就推荐，咳，推荐 smox 哈！

### Smox

smox 是我写的 react 的 vuex，它在 clicli 承担了 react 端的状态管理工作，最近更新了一下下，支持 react-hooks

```JavaScript
import React from 'react'
import { useSmox } from 'smox'

const mutations = {
  change(state) {
    state.sex = state.sex === 'boy' ? 'girl' : 'boy'
  }
}

const actions = {
  asyncChange({ commit }, payload) {
    setTimeout(() => {
      commit('change', payload)
    }, 1000)
  }
}

const state = {
  sex: 'boy'
}

export const Sex = () => {

  const [state, commit, dispatch] = useSmox(state, mutations, actions)
  
  return (
    <div>
      <h1>{state.sex}</h1>
      <button onClick={() => commit('change')}>变性</button>
      <button onClick={() => dispatch('asyncChange')}>异步变性</button>
    </div>
  )
}
```
（这么强上广告真的好么emmm）

### 业务逻辑的骚操作

大家可以看到，clicli 的业务逻辑真的非常骚，大概提一些不常见的：

**鹰嘴 css**

![](https://ws1.sinaimg.cn/large/0065Zy9egy1fwznzk3yyyj30fh09daa3.jpg)
这个效果很多人都想拥有吧，尤其是对话框，极为常见
这个效果还是很容易使用 css 实现的：

```css
:before{
    content: "";
    display: block;
    height: 10px;
    border-bottom-left-radius: 100%;
    position: absolute;
    top: 10px;
    left: 15px;
    border-right: 20px solid transparent;
    border-bottom: 15px solid rgb(33, 36, 58);
}
```
比较复杂一点的是这个：
![](https://ws1.sinaimg.cn/large/0065Zy9egy1fwznzjq6aoj30fv0930sz.jpg)
```css
:before,:after{
    z-index: 10;
    bottom: -12px;
    height: 10px;
    border-style: solid;
    border-width: 0 2px 2px 0;
    border-color: #f74687;
    display: block;
    content: "";
    position: absolute;
    transform: scaleX(-1);
}
:before{
    right: 18px;
    width: 20px;
    border-bottom-right-radius: 80px 50px;
    background: linear-gradient(108deg, transparent 8px, #fffffb 0);
}
:after{
    right: 17px;
    width: 8px;
    border-bottom-right-radius: 40px 50px;
}
```
然后还有，比如这个 blur 的效果：
![](https://dn-coding-net-production-pp.codehub.cn/25cd764d-551d-4818-b247-edf97a931f2f.png)

```css
div {
    background: #2b2e37;
    height: 200px;
    position: relative
    background:url('bg.jpg')
}
div:before {
    background:url('bg.jpg')
    content: "";
    width: 100%;
    height: 40px;
    position: absolute;
    top: 0;
    bottom: 0;
    background: #2b2e37;
    filter: blur(10px);
    z-index: 0;
}    
```
当然，对于一些常见的组件封装，能用 css 的肯定就不需要用 js

![](https://ws1.sinaimg.cn/large/0065Zy9egy1fwzo86knbaj308203m744.jpg)
没错，带文字的 switch 照样可以通过纯 css 来实现

```vue
<template>
  <div class="switch">
    <input class='switch-component' value="yes" type='radio' v-model="val" @click="switchDan">
    <span class="dan">弹</span>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        val: 'yes'
      }
    },
    methods: {
      switchDan() {
        this.val = this.val === 'yes' ? '' : 'yes'
        if(this.val==='yes'){
          this.$emit('openDm')
        }else {
          this.$emit('closeDm')
        }
      }
    }
  }
</script>

<style scoped lang="stylus">
  @import "~common/stylus/variable"
  .switch
    position relative
    margin-left 20px
    .switch-component
      width: 70px
      height: 36px
      background-color: #000
      border-radius: 36px
      border: none
      outline: none
      -webkit-appearance: none
      transition: all .2s ease
      cursor pointer
    .dan
      position: absolute
      top: 0
      left: 0
      width: 50%
      height: 36px
      background: $b-color
      border-radius: 50%
      transition: all .2s ease
      display inline-block
      text-align: center
      line-height: 36px
    .switch-component:checked
      background-color: #8e2b4f
    .switch-component:checked + .dan
      left: 50%
      color: #fff
      background $pink-color
</style>

```
啊不好意思，不小心说多了::>_<::
css的骚操作还有不少，可以去网站逛逛，然后看一下源码的::>_<::

**eplayer**

因为是视频网站，所以不得不自己写播放器和弹幕系统，别人的轮子是 hold 不住 c站 的逼格的

在写播放器的时候，也没啥好说的，就是传统的 dom 操作，但是也有一个 超级骚的操作，就是 html5 的 video 横屏

![](https://ws1.sinaimg.cn/large/0065Zy9egy1fwzogl2l8aj30jk0ncgmf.jpg)

这个效果其实是非常难实现的，原因是有个 css 的超级大坑！
就是 fixed 和 transform 存在层级关系时，是无效的

但是对于 css 闭眼写的我而言，我特么还是解决了（感动自己）

```html 
<div class="fixed">
  <div class="transform-rotate">
    <li>left</li>
  </div>
</div>
```
```css
.fixed {
  position: fixed;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  background: #000;
}

.transform-rotate {
  position: fixed;
  top: 0;
  bottom: 0;
  transform-origin: 0 50%;
  transform: rotate(-90deg) translate(-50%, 50%);
}
```
这两段代码，就可以实现一个几乎失效的 demo，需要注意的是 transform 的 translate，这个是为了接下来的计算

到这里，div 是 已经旋转 90度 了，但是因为 fixed 失效了，所以没办法撑开全屏
先强制给宽高
```javascript
this.player.style.height = window.innerWidth + 'px'
this.player.style.width = window.innerHeight + 'px'
```
然后我们需要寻找一个至今没人找到的计算方式，强制给 transform

```javascript
let ot = -(this.player.getBoundingClientRect().top + window.innerHeight / 2) + 'px'
this.player.style.transform = `rotate(-90deg) translate(${ot}, 50%)`
```

然后就找到了，这段的重点是 `getBoundingClientRect()` 和 第二次 translate

然后纯 html5 的全屏和 transform 和 fixed 的万年大坑终于算是填上了

至于弹幕，因为不够通用，这里先不写了（实际上是也不知道写啥）……

**node中间层**

从上面的架构图中，可以看到 koa 作为中间层，要负责 ssr，除了 ssr，我们网站还有一个非常强大的解析系统，会通过 node 来做

在解析的过程中，要跨过各大网站的加密、限制

比如 302 限制，就是说，我们需要拿到 302 的 res 的 headers 的 location
正常是拿不到的肯定，说实话之前我是用 php 的 curl 拿的

后来发现 node 也能做：
```javascript
const http = require('http')

const options = {
    host: 'www.xxoo.com',
    path: '/xoxo',
    headers: {
        'user-agent': 'curl/7.31.0'
    }
};

var req = http.get(options, function(res) {
   console.log(res.headers.location)
})
```

### 总结

c站 还在不断重构，还在不断进步，文章只是提到一丢丢，伴随着 c站 的重构，后续还有很多分享！

c站 所有的源码都在这里：https://github.com/132yse/acgzone

然后其他源码地址：
smox：https://github.com/132yse/smox
eplayer：https://github.com/132yse/eplayer

那个，看在我开源所有代码的份儿上，给 star 一定要给 smox ！哈！
