### ISSUE TITLE
CSS【日常处理总结】

### ISSUE THREAD

**Issue by yiranjason** [frontend9/fe9-library#204]
# CSS『日常CSS处理总结』

> CSS其实“不简单”，控制好样式是实现美观第一步。你觉得呢？

## [Case1]DIV 水平垂直居中
_/*通常考虑时看需要操作的div的宽高属性，分为定宽高和不定宽高两种情况处理*/_<br />_<br />**定义一个盒子，以助于理解：**
```html
<div class="Golden">
  	<div class="box size">内容存放-JasonSubMara</div>
</div>
```
**处理方式：**
* 盒子定宽高时：
```css
.Golden {border:1px solid #ddd; width:300px; height:300px;}
.box {background:#f99;}
.box.size {width:100px; hieght:100px;}
```
```css
/*01.absolute+负margin*/
.Golden {position:relative;}
.box {position:absolute; left:50%; top:50px; margin-left:-50px; margin-top:-50px;}

/*02.absolute+margin auto*/
.Golden {position:relative;}
.box {position:absolute; left:0; top:0; right:0; bottom:0; margin:auto;}

/*03.absolute+calc*/
.Golden {position:relative;}
.box {position:absolute; top:calc(50% -50px); left:(50% -50px);}
```

* 盒子不定宽高时：
```css
/*01.absolute+transform*/
.Golden {position:relative;}
.box {position:absolute; top:50%; left:50%; transform(-50%,-50%);}
/*-------->>>>>>>這種方法需要考慮transform,即translate2d得兼容性*/

/*02.lineheight*/
.Golden {line-height:300px; text-align:center; font-size:0px;}
.box {font-size:16px; display:inline-block; vertical-align:middle; line-height:initital; text-align:left;}

/*03.writimg-mode*//*----->>>>>>>>>>#########神奇的用法，來源于【張鑫旭】##########<<<<<<<<-------------*/
/*---->>>>使用這個屬性方法時候。需要有一定條件：其結構變成了<div.Golden><div.Golden-inner><div.box></div></div></div>*/
.Golden {writing-mode:vertical-lr; text-align:center;}
.Golden-inner {writing-mode:horizontal-tb; display:inline-block; text-align:center; width:100%;}
.box {display:inline-block; margin:auto; text-align:left;}

/*04.css-table*/
.Golden {display:table-cell; text-align:center; vertical-align:middle;}
.box {display:inline-block;}

/*05.flex*/
.Golden {display:flex; justify-content:center; align-items: center;}

/*06.grid*/
.Golden {display:grid;}
.box {align-self:center; justify-self:center;}
```

---
## [case2]文本内容的颜色渐变实现
<br /><br />**处理方式：**
```css
/*case01: mask-image*/

.text-gradient {
    display:inline-block;
    font-family:"微软雅黑";
    font-size:10em;
    position:relative;
}
.text-gradient[data-text]::after {
    content:attr(data-text);
    color:green;
    position:absolute;
    left:0;
    z-index:2;
    -webkit-mask-image:-webkit-gradient(linear,0,0,0 bottom, from(#ff0000),to(rgba(0,0,255,0)));
}


/*case02: background-clip + text-fill-color*/

.text-gradient {
    display:inline-block;
    font-family:"微软雅黑";
    font-size:10em;
    color:green;
    background-image:-webkit-gradient(linear,0,0,0 bottom, from(rgba(0,128,0,1),to(rgba(51,51,51,1)));
    -webkit-background-clip:text;
    -webkit-text-fill-color:transparent;
}
```

---
## [case3]纯CSS绘制三角形
![微信图片_20190109132740.png](https://cdn.nlark.com/yuque/0/2019/png/238022/1547011678349-e167b56c-57de-49a1-8591-89b11ecd8646.png#align=left&display=inline&height=306&linkTarget=&name=%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20190109132740.png&originHeight=408&originWidth=99&size=3617&width=74)   **效果如左示图**

```css
/*示例图中的实心三角形*/
#triangle_up {
  width:0; height:0; 
  border-left:30px solid transparent; 
  border-right:30px solid transparent; 
  border-bottom:100px solid red;}
#triangle_down {width:0; height:0; 
  border-left:30px solid transparent; 
  border-right:30px solid transparent; 
  border-top:60px solid blue;}
#triangle_left {width:0; height:0; 
  border-top:30px solid transparent; 
  border-bottom:30px solid transparent; 
  border-right:60px solid green;}
#triangle_right {width:0; hieght:0; 
  border-top:30px solid transparent; 
  border-bottom:30px solid transparent; 
  border-left:60px solid yellow;}

/*示例图中的空心三角形【箭头】*/
#Hollowtriangle {width:0; height:0; 
  border-top:90px solid transparent; 
  border-right:100px solid black; 
  border-bottom:100px solid transparent; 
  position:relative;}
#Hollowtriangle::after {content: '';
  position:absolute; 
  top:-89px; 
  left:20px; 
  border-top:89px solid transparent; 
  border-bottom:99px solid transparent; 
  border-right:99px solid #fff;}
```
